use serde::Deserialize;

#[derive(Debug, Deserialize)]
pub struct Options {
    pub put_call: String,
    pub symbol: String,
    pub description: String,
    pub exchange_name: String,
    pub bid: f32,
    pub ask: f32,
    pub last: f32,
    pub mark: f32,
    pub bid_size: String,
    pub ask_size: String,
    pub bid_ask_size: String,
    pub last_size: String,
    pub high_price: f32,
    pub low_price: f32,
    pub open_price: f32,
    pub close_price: f32,
    pub total_volume: String,
    pub trade_date: String,
    pub trade_time_in_long: String,
    pub quote_time_in_long: String,
    pub net_change: String,
    pub volatility: String,
    pub delta: f32,
    pub gamma: f32,
    pub theta: f32,
    pub vega: f32,
    pub rho: f32,
    pub open_interest: String,
    pub time_value: String,
    pub theoretical_option_value: String,
    pub theoretical_volatility: String,
    pub option_deliverables_list: String,
    pub strike_price: f32,
    pub expiration_date: i64, // This is a unix timestamp
    pub days_to_expiration: String,
    pub expiration_type: String,
    pub last_trading_day: String,
    pub multiplier: String,
    pub settlement_type: String,
    pub deliverable_note: String,
    pub is_index_option: String,
    pub percent_change: String,
    pub mark_change: String,
    pub mark_percent_change: String,
    pub intrinsic_value: String,
    pub in_the_money: String,
    pub non_standard: String,
    pub mini: String,
    pub penny_pilot: String,
    pub option_symbol: String,
    pub expiry: String,
    pub strike: String,
    pub close: String,
    pub quote_date: String
}
