pub struct ChainsApiResponse {
    pub symbol: String,
    pub status: String,
    pub underlying: Underlying,
    pub strategy: String,
    pub interval: i64,
    pub is_delayed: bool,
    pub is_index: bool,
    pub days_to_expiration: i64,
    pub interest_rate: f64,
    pub underlying_price: f64,
    pub volatility: f64,
    pub call_exp_date_map: CallExpDateMap,
    pub put_exp_date_map: PutExpDateMap,
}

pub struct Underlying {
    pub ask: f64,
    pub ask_size: i64,
    pub bid: f64,
    pub bid_size: i64,
    pub change: f64,
    pub close: f64,
    pub delayed: bool,
    pub description: String,
    pub exchange_name: String,
    pub fifty_two_week_high: f64,
    pub fifty_two_week_low: f64,
    pub high_price: f64,
    pub last: f64,
    pub low_price: f64,
    pub mark: f64,
    pub mark_change: f64,
    pub mark_percent_change: f64,
    pub open_price: f64,
    pub percent_change: f64,
    pub quote_time: i64,
    pub symbol: String,
    pub total_volume: i64,
    pub trade_time: i64,
}

pub struct CallExpDateMap {
    pub additional_prop1: AdditionalProp,
    pub additional_prop2: AdditionalProp,
    pub additional_prop3: AdditionalProp,
}

pub struct PutExpDateMap {
    pub additional_prop1: AdditionalProp,
    pub additional_prop2: AdditionalProp,
    pub additional_prop3: AdditionalProp,
}


pub struct AdditionalProp {
    pub put_call: String,
    pub symbol: String,
    pub description: String,
    pub exchange_name: String,
    pub bid_price: f64,
    pub ask_price: f64,
    pub last_price: f64,
    pub mark_price: f64,
    pub bid_size: i64,
    pub ask_size: i64,
    pub last_size: i64,
    pub high_price: f64,
    pub low_price: f64,
    pub open_price: f64,
    pub close_price: f64,
    pub total_volume: i64,
    pub trade_date: i64,
    pub quote_time_in_long: i64,
    pub trade_time_in_long: i64,
    pub net_change: f64,
    pub volatility: f64,
    pub delta: f64,
    pub gamma: f64,
    pub theta: f64,
    pub vega: f64,
    pub rho: f64,
    pub time_value: f64,
    pub open_interest: i64,
    pub is_in_the_money: bool,
    pub theoretical_option_value: f64,
    pub theoretical_volatility: f64,
    pub is_mini: bool,
    pub is_non_standard: bool,
    pub option_deliverables_list: Vec<OptionDeliverables>,
    pub strike_price: f64,
    pub expiration_date: String,
    pub days_to_expiration: i64,
    pub expiration_type: String,
    pub last_trading_day: i64,
    pub multiplier: i64,
    pub settlement_type: String,
    pub deliverable_note: String,
    pub is_index_option: bool,
    pub percent_change: f64,
    pub mark_change: f64,
    pub mark_percent_change: f64,
    pub is_penny_pilot: bool,
    pub intrinsic_value: f64,
    pub option_root: String,
}

pub struct OptionDeliverables {
    pub symbol: String,
    pub asset_type: String,
    pub deliverable_units: String,
    pub currency_type: String,
}

