# curl -X 'GET'
#  'https://api.schwabapi.com/marketdata/v1/quotes?symbols=AAPL&fields=quote&indicative=false'
#  -H 'accept: application/json'
#  -H 'Authorization: Bearer I0.b2F1dGgyLmJkYy5zY2h3YWIuY29t.0ofwnZsm6rg_DFywvztCQqqBRWCnDl76kflcCMpRxfg@'
#GET https://api.schwabapi.com/marketdata/v1/quotes?symbols=AAPL&fields=quote&indicative=false
GET https://api.schwabapi.com/marketdata/v1/quotes?symbols=AAPL&fields=quote&indicative=false
accept: application/json
#Authorization: Bearer I0.b2F1dGgyLmJkYy5zY2h3YWIuY29t.0ofwnZsm6rg_DFywvztCQqqBRWCnDl76kflcCMpRxfg@
Authorization: Bearer I0.b2F1dGgyLmNkYy5zY2h3YWIuY29t.Ck-rjjJ_yD-gIBx0Su2eWOn9Wf8bCWKTRiJ4Zn7nywY@
###


